### ISSUE TITLE
"Azure Login" Workflow step fails

### ISSUE THREAD

**Issue by gmlunesa** [gmlunesa/methical#5]
## Details

Getting the following exception when trying to generate an OpenAPI Specification Document with Swagger

```
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
```

| PR #2   | [Github Action](https://github.com/gmlunesa/methical/actions/runs/3764598164/jobs/6399344016#step:4:26)  |
| ------------- | ------------- |

## Step
```yml
- name: Azure Login
  uses: azure/login@v1
  with:
    creds: ${{ secrets.MethicalNetApiManagement_SPN }}
```
<details><summary>Stack Trace</summary>
```
Run azure/login@v1
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
</details>

## Possible solutions

Azure/login/issues/205
